### ISSUE TITLE
Generate trait attribute breaks test

### ISSUE THREAD

**Issue by barretodavid** [starknet-edu/counter-workshop#4]
When implementing the required steps using `#[generate_trait]` instead of creating a trait marked with `#[starknet::interface]` the test fails because it can't import the associated dispatcher

**Comment by barretodavid** [comment]
Also, we should specify that the test expects the trait to be called `ICounter`. Any other name like `CounterTrait` would break the test.

**Comment by robertkodra** [comment]
Done! :shipit:
