### ISSUE TITLE
Clarify instructions for step3

### ISSUE THREAD

**Issue by barretodavid** [starknet-edu/counter-workshop#5]
We should make it clearer that the expected argument for the constructor is the address of the killswitch. We should also mention somewhere what's the address of the KillSwitch smart contract on Goerli in case they want to deploy the Counter contract

**Comment by barretodavid** [comment]
I saw that the address of the KillSwitch contract is provided in step 4, maybe we should bump it to step 3 for clarity

**Comment by robertkodra** [comment]
Added additional information to this. Thanks for the suggestion! :shipit:
