### ISSUE TITLE
step4 Test failure

### ISSUE THREAD

**Issue by qiaopengjun5162** [starknet-edu/counter-workshop#58]
step4 Test failure  

➜ scarb test 
     Running test counter (snforge test)
error: Identifier not found.
 --> /Users/qiaopengjun/Code/cairo/counter-workshop/tests/test_step.cairo:2:14
use counter::counter::{ICounterDispatcher, ICounterDispatcherTrait};
             ^*****^

error: Identifier not found.
 --> /Users/qiaopengjun/Code/cairo/counter-workshop/tests/test_step.cairo:2:14
use counter::counter::{ICounterDispatcher, ICounterDispatcherTrait};
             ^*****^

error: Method `get_counter` not found on type `<missing>`. Did you import the correct trait and impl?
 --> /Users/qiaopengjun/Code/cairo/counter-workshop/tests/test_step.cairo:9:37
    let stored_counter = dispatcher.get_counter();
                                    ^*********^

warning: Unused variable. Consider ignoring by prefixing with `_`.
 --> /Users/qiaopengjun/Code/cairo/counter-workshop/tests/test_step.cairo:7:9
    let contract_address = deploy_contract(initial_counter);
        ^**************^

Error: Failed to compile test artifact, for detailed information go through the logs above
[ERROR] Failed to build test artifacts with Scarb: `scarb` exited with error

test_step.cairo

use super::utils::deploy_contract;
use counter::counter::{ICounterDispatcher, ICounterDispatcherTrait};

#[test]
fn check_stored_counter() {
    let initial_counter = 12;
    let contract_address = deploy_contract(initial_counter);
    let dispatcher = ICounterDispatcher { contract_address };
    let stored_counter = dispatcher.get_counter();
    assert!(stored_counter == initial_counter, "Stored value not equal");
}

counter.cairo 

#[starknet::interface]
trait ICounter<TContractState> {
    fn get_counter(self: @TContractState) -> u32;
}

#[starknet::contract]
mod Counter {
    use super::ICounter;

    #[storage]
    struct Storage {
        counter: u32
    }

    #[constructor]
    fn constructor(ref self: ContractState, counter: u32) {
        self.counter.write(counter);
    }

    #[abi(embed_v0)]
    impl ICounterImpl of ICounter<ContractState> {
        fn get_counter(self: @ContractState) -> u32 {
            self.counter.read()
        }
    }
}

utils.cairo

use starknet::{ContractAddress};
use snforge_std::{declare, cheatcodes::contract_class::ContractClassTrait};

pub fn deploy_contract(initial_value: u32) -> ContractAddress {
    let contract = declare("Counter").unwrap();
    let constructor_args = array![initial_value.into()];
    let (contract_address, _) = contract.deploy(@constructor_args).unwrap();
    contract_address
}

**Comment by qiaopengjun5162** [comment]
scscarb --version

scarb 2.6.5 (d49f54394 2024-06-11)
cairo: 2.6.4 (https://crates.io/crates/cairo-lang-compiler/2.6.4)
sierra: 1.5.0

**Comment by ChapuKosi** [comment]
hey, 
the issue is with how the naming is done
to correct it, in your counter.cairo file change ```mod Counter{}``` to ```mod counter_contract{}```

```diff

#[starknet::contract]
-mod Counter {
    #[storage]
    struct Storage {
        counter: u32,
    }
    ...
   }
   
   
#[starknet::contract]
+mod counter_contract {
    #[storage]
    struct Storage {
        counter: u32,
    }
    ...
   }
```

drop a message if the test works now for you !!
